"use strict";
exports.__esModule = true;
var express_1 = require("express");
var multer_1 = require("multer");
var upload = (0, multer_1["default"])();
var router = express_1["default"].Router();
var upload_1 = require("../controllers/upload");
router.post('/', upload.single('file'), upload_1.uploadImage);
router["delete"]('/:id', upload_1.deleteImage);
exports["default"] = router;
